### ISSUE TITLE
Bad Method Call

### ISSUE THREAD

**Issue by Ajibolarilwan14** [LaravelDaily/laravel-charts#107]
I got this error while trying to use this package in my Laravel 7 app, I've tried many solutions online but all efforts prove abortive, any help?

Symfony\Component\ErrorHandler\Error\FatalError
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Undefined index: data (View: /Users/loyaltysolutions/easycollectapp/vendor/laraveldaily/laravel-charts/src/views/javascript.blade.php)

**Comment by PovilasKorop** [comment]
@Ajibolarilwan14 sorry but we don't actively support versions as old as Laravel 7 so I can't really debug to help

**Comment by Ajibolarilwan14** [comment]
Okay, thanks for your reply!
