### ISSUE TITLE
error :  undefined array key "stacked" 

### ISSUE THREAD

**Issue by comsatsTaha** [LaravelDaily/laravel-charts#109]
$chartOptionsDaily = [
            'chart_title' => 'Per Day Applications',
            'report_type' => 'group_by_date',
            'model' => 'App\Models\Candidate',
            'group_by_field' => 'created_at',
            'group_by_period' => 'day',
            'chart_type' => 'bar',
            'chart_color' => '255,0,0',
        ];
        $chartDaily = new LaravelChart($chartOptionsDaily);
        
        
        
  Error Showing on : 
{!! $chartDaily ->renderJs() !!}

**Comment by PovilasKorop** [comment]
@comsatsTaha add option `'stacked' => false`, we will fix this in the next release.
