### ISSUE TITLE
Relationship and also group by specific table

### ISSUE THREAD

**Issue by impactcolor** [LaravelDaily/laravel-charts#13]
Currently I have the following options:
```
      $chart_options = [
        'chart_title' => 'Stats by dates',
        'chart_type' => 'bar',
        'report_type' => 'group_by_relationship',
        'model' => 'App\Operator',

        'relationship_name' => 'user',
        'group_by_field' => 'name',

        'filter_field' => 'completed_date',
        'filter_days' => 1,
        'filter_period' => 'week',
      ];
```
In date from model Operator I have a table item_clicked.  I'd like to display
"where item_clicked == 'byname' ONLY and keep all the rest the same.  Is there anyway to achieve custom queries for the data?

**Comment by PovilasKorop** [comment]
@impactcolor currently we don't have any function to filter results with custom `where` queries, we have `where` only on dates: https://github.com/LaravelDaily/laravel-charts/blob/e9d93a9856876cfbee946de101b3be5679dfd654/src/Classes/LaravelChart.php#L39

Technically, accepting any where parameters (fields, values) could be a potential security issue, cause we can't control it. 

So your options are:
- Add a Pull Request to the package to make it work with `where`
- Fork the package to your own and make any edits you want
- Copy-paste the code from the package to your internal class in your Laravel project and make any edits you want
- Change the charts code to not use this package

**Comment by PovilasKorop** [comment]
Fixed in https://github.com/LaravelDaily/laravel-charts/releases/tag/0.1.15
