### ISSUE TITLE
I want to create mixed chart 

### ISSUE THREAD

**Issue by PRVN007** [LaravelDaily/laravel-charts#16]
Hey, 
I want to create mixed chart.

**Comment by PovilasKorop** [comment]
@PRVN007 what do you call mixed chart? Give a link or screenshot example, please

**Comment by PRVN007** [comment]
[my-point.pptx](https://github.com/LaravelDaily/laravel-charts/files/3950005/my-point.pptx)
@PovilasKorop  Please check  .

**Comment by PRVN007** [comment]
![mixed](https://user-images.githubusercontent.com/51471690/70616747-25b9cf00-1c35-11ea-9134-9637b1b7b765.png)
@PovilasKorop Please check

**Comment by PovilasKorop** [comment]
@PRVN007 oh now I understand. Currently this package doesn't support such charts, sorry
