### ISSUE TITLE
How to add x-axis and y-axis labels text for chart type =  bar

### ISSUE THREAD

**Issue by matheenulla6** [LaravelDaily/laravel-charts#17]
Hi 
I just want to add the x-axis and y-axis label text manually and change the colors in the pie chart. Please tell me how to add

thank you 

![Screenshot_1](https://user-images.githubusercontent.com/37471028/70904460-6fd0f500-2027-11ea-9546-607a4eae779d.png)
![Screenshot_2](https://user-images.githubusercontent.com/37471028/70904499-8a0ad300-2027-11ea-937b-e4fcfd30d8e6.png)

**Comment by PovilasKorop** [comment]
@matheenulla6 we don't have such customizations, our package is for simple and quick charts, sorry.

**Comment by matheenulla6** [comment]
@PovilasKorop  can we able to change colors?

**Comment by PovilasKorop** [comment]
@matheenulla6 from what I remember, colors are assigned randomly every time, and no there's no way to customize them. But if you write that code, we will accept that Pull Request.

**Comment by matheenulla6** [comment]
@PovilasKorop  thank you for your response.
