### ISSUE TITLE
Fails if imagick extension not installed

### ISSUE THREAD

**Issue by noxidsoft** [LaravelDaily/laravel-charts#18]
Just a heads up, spatie library requires imagick to run, including Dashboard & Reports on an application, this returns an error after GIT download to local machine running on Windoze.

Symfony\Component\Debug\Exception\FatalThrowableError
Class 'LaravelDaily\LaravelCharts\Classes\LaravelChart' not found 

So, I attempt an install of that package...

Windows 10 WAMP

$ composer require laraveldaily/laravel-charts
Using version ^0.1.13 for laraveldaily/laravel-charts
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - Installation request for spatie/pdf-to-image (locked at 1.8.2) -> satisfiable by spatie/pdf-to-image[1.8.2].

Really is a WAMP issue on Windows, but just a note that these users will run into the issue. Suggest alternative chart support in future development. Recommend a user include a non-CRUD blank menu item/view to implement their own Dashboard etc.

**Comment by PovilasKorop** [comment]
@noxidsoft `imagick` requirement is not inside of this `laravel-charts` package.
See `composer.json`, the require list is absolutely empty: https://github.com/LaravelDaily/laravel-charts/blob/master/composer.json

It comes from `Laravel MediaLibrary` which we use in code of QuickAdminPanel for file uploads. So when you ran `composer require`, your previous installation ran into that issue.

And we mentioned imagick in installation instructions: https://2019.quickadminpanel.com/pages/downloading-panel-installing

Unfortunately, there's not much we can do about it - Spatie guys promised to remove this dependency, but later changed their mind cause it's a big task for them and not a priority. And for us, we can't change Laravel MediaLibrary to something else, it would be months of work to change to WORSE functionality.

So I understand the issue, but unfortunately you have to install imagick on your server.

**Comment by noxidsoft** [comment]
Completely understand, thank you for the information, makes sense. I use Matomo, so I was able to just include the widgets on the Dashboard instead, and I like the workaround (: 
Thank you for the help.
