### ISSUE TITLE
big amount of data with laravel collection 

### ISSUE THREAD

**Issue by ihabhamad** [LaravelDaily/laravel-charts#19]
hi LaravelDaily Team
Laravel collection is a very bad idea if the table is a big amount of data
 $collection = $query->get();
return error 500

**Comment by PovilasKorop** [comment]
@ihabhamad without a full example I can't comment on anything, collection in itself is not a bad idea, maybe bad idea is your table structure or the way you are filtering the data, maybe that returns too big amount of data.

**Comment by ihabhamad** [comment]
@PovilasKorop  I know laravel collection is awesome exactly ( we can use it as elequent quires )  and your package is very powerful but if my table have 10k rows daily and want to show only 7 days  chart we have 70k rows , the laravel collection can't handle it  my table calls details records  laravel standard table will be send to you table structure and the error code after  I back to my office

**Comment by PovilasKorop** [comment]
Closing as didn't get more information from the issue author.
