### ISSUE TITLE
Sampling data by value

### ISSUE THREAD

**Issue by zKoz210** [LaravelDaily/laravel-charts#20]
Is it possible to make a selection of data by ID?

Purchases (user_id, amount, and etc) 

How make chart only for user with ID = 1?

**Comment by PovilasKorop** [comment]
@zKoz210 currently there is no such filtering feature.

**Comment by PovilasKorop** [comment]
Fixed in https://github.com/LaravelDaily/laravel-charts/releases/tag/0.1.15
