### ISSUE TITLE
unable to display data in graph

### ISSUE THREAD

**Issue by sarojbrt1** [LaravelDaily/laravel-charts#21]
<div class="container">
  <div class="row">
  <div class="col-md-12">
  <div class="card">
  <div class="card-header">Dashboard</div>
   <div class="card-body">  
   <h1>Users by months</h1>
   <canvas id="users_by_months"></canvas> 
  <hr /> 
   <h1>Users by names</h1>
  <canvas id="users_by_names"></canvas>
   <hr /> 
  </div> 
   </div>
  </div>
 </div>
 </div>

**Comment by PovilasKorop** [comment]
Please check if you loaded javascript/jquery, or if there is any error in browser development console.
