### ISSUE TITLE
Undefined offset: 0 /vendor/laraveldaily/laravel-charts/src/views/javascript.blade.php

### ISSUE THREAD

**Issue by hashmat0811** [LaravelDaily/laravel-charts#22]
I've installed the package on Laravel 6 using 
`composer require laraveldaily/laravel-charts`

But It is showing error on my view: 

> Undefined offset: 0 (View: /var/www/html/my-project/vendor/laraveldaily/laravel-charts/src/views/javascript.blade.php)

![FireShot Capture 121 - 🧨 Undefined offset_ 0 (View_ _var_www_html_hthc-backend_vendor_larav_ - 127 0 0 1](https://user-images.githubusercontent.com/34671872/79748007-48b66700-832a-11ea-9d98-54411dc873f2.png)

Any help will be appreciated.

**Comment by PovilasKorop** [comment]
@hashmat0811 you probably have put some parameter wrong, can you double check with documentation in Readme file?

If you still can't figure it out, please show the code of LaravelChart calling and what parameters you're using, in controller or somewhere else, then I will be able to comment

**Comment by hashmat0811** [comment]
Thanks, @PovilasKorop for the reply, I've copied the same code of **Using Multiple Charts** in the readme for testing it.

**Comment by PovilasKorop** [comment]
@hashmat0811 reproduced it myself, too. And fixed, release a new version: https://github.com/LaravelDaily/laravel-charts/releases/tag/0.1.16

Please run `composer update`

The error happened when there was no data for the chart.
