### ISSUE TITLE
Multiple records with same result doesnt show

### ISSUE THREAD

**Issue by tommiekn** [LaravelDaily/laravel-charts#24]
Hi,

I have noticed that in a line graph, with multiple conditions, if two or more conditions have the same result number, only one shows in the graph while hover it.

I believe that if multiple conditions has the same result these shall be all listed in the hover tooltip of the chart.

**Comment by PovilasKorop** [comment]
@tommiekn that could be a feature/bug in Chart.js library we use. Can you attach a screenshot/screencast how to reproduce?

**Comment by tommiekn** [comment]
@PovilasKorop hi, i would avoid to attach a screenshot cause the chart is showing api endpoints.

Anyway is simply a chart where i know theres multiple voices with the same total result, and only one shows.

For reference, it should be working like this (this is an official Spotify Api chart):
In this example many records has 0 as result so while onmouse over it shows all of them.

![Screen Shot 2020-05-09 at 11 54 07](https://user-images.githubusercontent.com/24386363/81470627-ed221f80-91eb-11ea-9929-c4052da05096.png)

Heres the chart code i am using:

```
$chart_options_request_endpoint = [
            'chart_title' => 'Number of Requests/Endpoint',
            'chart_type' => 'line',
            'report_type' => 'group_by_date',
            'model' => 'App\ApiLog',
            'conditions'            => [
                ['name' => 'name 1', 'condition' => 'url = "asd" and response = "200"', 'color' => 'black'],
                ['name' => 'name2', 'condition' => 'url = "asd1" and response = "200"', 'color' => 'green'],
['name' => 'name 3', 'condition' => 'url = "asd2" and response = "200"', 'color' => 'blue'],
            ],
            
            'group_by_field' => 'created_at',
            'group_by_period' => 'day',
            
            //'aggregate_function' => 'sum',
            //'aggregate_field' => 'id',
            
            
            'filter_field' => 'created_at',
            'filter_days' => 30, // show only transactions for last 30 days
            'filter_period' => 'month', // show only transactions for this week
            'continuous_time' => false, // show continuous timeline including dates without data
        ];
        
```

Thanks!

**Comment by tommiekn** [comment]
I have checked Chart.js library docs and i believe what you miss is to specify the index value in the Chart.js options:

https://www.chartjs.org/docs/latest/general/interactions/modes.html#interaction-modes

You should add:

```
tooltips: {
    mode: 'index'
},
```

I did not test this yet but 99% this is the issue.

**Comment by tommiekn** [comment]
opened this one:
https://github.com/LaravelDaily/laravel-charts/pull/26

I believe would be a good idea to move some of these js settings to the plugin options, including this field.
