### ISSUE TITLE
continuous_time gives error

### ISSUE THREAD

**Issue by tommiekn** [LaravelDaily/laravel-charts#28]
Hi, 

If i enable continuous_time with a graph that works on a dataset with only the last 4 days set (its a log table) , it gives error:

"Invalid start date."
LaravelChart.php line 119

**Comment by PovilasKorop** [comment]
@tommiekn can you give more details on "only the last 4 days set"? What is the actual data in DB (any screenshots or anything) and what parameters are you putting into LaravelChart? Otherwise, I can't reproduce/help.
