### ISSUE TITLE
Line charts and conditions issue

### ISSUE THREAD

**Issue by tommiekn** [LaravelDaily/laravel-charts#29]
Hi,

Line charts with multiple conditions should have all conditions to 0 on each day(or month or what so ever is selected) if theres no records for that conditions in the recordset.

Now this doesnt happen, if i do have 10 conditions, but the script can retrieve records only for 1, it doesnt show the other 9 with a "0 value", that should be the way it works i believe.

**Comment by PovilasKorop** [comment]
@tommiekn can you share the code of parameters you're putting in LaravelChart? Will be much easier to reproduce, then.
