### ISSUE TITLE
Is there way to make equable time axis, for show absent objects?

### ISSUE THREAD

**Issue by mixartemev** [LaravelDaily/laravel-charts#3]
If there is not objects in some date, then this date is cut out from chart.
<img width="781" alt="Снимок экрана 2019-06-13 в 11 51 13" src="https://user-images.githubusercontent.com/5181924/59418904-82e1de80-8dd2-11e9-9272-531af87289e3.png">
And I want to show created objects in EVERY day from last month, including days when objects is not created.

**Comment by PovilasKorop** [comment]
@mixartemev yes it's a known issue. Probably it requires a loop after results are formed, to fill in empty dates into array. If you have time, please try to do a PR, otherwise we will probably fix it some day but not in nearest future, have other priorities with QuickAdminPanel currently.
