### ISSUE TITLE
ErrorException No hint path defined for [laravelchart].

### ISSUE THREAD

**Issue by mohosin16103308** [LaravelDaily/laravel-charts#31]
ErrorException
No hint path defined for [laravelchart].
![error](https://user-images.githubusercontent.com/32362094/83151471-6e4f4100-a11e-11ea-9115-5f7142732dc2.PNG)
Would you please help me how I solve this issue.
I am using :         "laravel/framework": "5.4.*",

**Comment by PovilasKorop** [comment]
@mohosin16103308 we haven't tried it with that old Laravel version, likely this package won't work on Laravel 5.4, sorry.

**Comment by mohosin16103308** [comment]
Ok Thank You
