### ISSUE TITLE
group_by_field_format missing in documentation

### ISSUE THREAD

**Issue by neppoz** [LaravelDaily/laravel-charts#32]
Hi,

i initially struggled to to set the correct datetime format when grouping by a datetime field. So i noticed in LaravelChart the undocumented group_by_field_format

LaravelChart.php Line 106
`$this->options['group_by_field_format'] ?? 'Y-m-d H:i:s',`

Could be useful for those using CET time settings or those who have model mutators otherwise the query will fail.

**Comment by PovilasKorop** [comment]
@neppoz thanks for noticing! Would you be able to add it to the documentation as a Pull Request, please?

**Comment by neppoz** [comment]
For sure. Please see https://github.com/LaravelDaily/laravel-charts/pull/33

**Comment by PovilasKorop** [comment]
Fixed.
