### ISSUE TITLE
How do I change the date format?

### ISSUE THREAD

**Issue by Overx** [LaravelDaily/laravel-charts#35]
How do I change the date format? for example: created_at->format('d/m/Y')

**Comment by PovilasKorop** [comment]
@Overx we have only this as a parameter:

`group_by_field_format` (optional), set the expected php date format. Examples: "d.m.Y", "d-m-Y";

Nothing more about date formats. So if you want some other behavior for date formats, we're happy to accept a Pull Request.

**Comment by Overx** [comment]
> `group_by_field_format`

Very thx, working Fine!
