### ISSUE TITLE
How to assign a style class to the canvas?

### ISSUE THREAD

**Issue by Overx** [LaravelDaily/laravel-charts#36]
`<canvas id="{{ $options['chart_name'] ?? 'myChart' }}"></canvas>`

it would be interesting to have a new attribute

`<canvas id="{{ $options['chart_name'] ?? 'myChart' }}" class="{{ $options['class_name']  }}"></canvas>`

**Comment by PovilasKorop** [comment]
@Overx currently we're not planning to spend time on new features for this package, but we are happy to accept it as a Pull Request if you create it.

**Comment by Overx** [comment]
> currently we're not planning to spend time on new features for this package, but we are happy to accept it as a Pull Request if you create it.

Ok, I'm going to clone the repository and make some changes and send it to you
