### ISSUE TITLE
how use where_raw ?

### ISSUE THREAD

**Issue by vanvat11** [LaravelDaily/laravel-charts#38]
how use where_raw ?

**Comment by PovilasKorop** [comment]
@vanvat11 see this example from Pull Request: https://github.com/LaravelDaily/laravel-charts/pull/37/files#diff-e56a33fda96f806bcc3d7dd046dc2934R88

It just adds Eloquent's `whereRaw()` method with whatever you specify with `where_raw()` parameter.

**Comment by Overx** [comment]
> @vanvat11 see this example from Pull Request: https://github.com/LaravelDaily/laravel-charts/pull/37/files#diff-e56a33fda96f806bcc3d7dd046dc2934R88
> 
> It just adds Eloquent's `whereRaw()` method with whatever you specify with `where_raw()` parameter.

You can create conditions from simple to advanced, example:

`budgets.project_id = projects.id` or `1 = (SELECT COUNT(*) FROM budgets WHERE budgets.project_id = projects.id)`
