### ISSUE TITLE
Include SoftDelete

### ISSUE THREAD

**Issue by Jipem** [LaravelDaily/laravel-charts#39]
Hello,
I use SoftDelete on some Models.
How can I include this in my stats (to know the number of delete items) ?
Thanks !

**Comment by PovilasKorop** [comment]
@Jipem in general, you would do that in Eloquent by using `withTrashed()` method but we don't have this feature inside of this package, we're just querying the model.

But if you want to spend time on this and make a Pull Request to the package, we're happy to consider it.
