### ISSUE TITLE
"N+1 query" problem when report type is "group_by_relationship"

### ISSUE THREAD

**Issue by mixartemev** [LaravelDaily/laravel-charts#4]
<img width="1344" alt="Снимок экрана 2019-06-13 в 13 40 31" src="https://user-images.githubusercontent.com/5181924/59428192-48357180-8de5-11e9-93f7-88d4060e22e9.png">

**Comment by PovilasKorop** [comment]
@mixartemev ok released `0.1.8` version, thanks for Pull Request!
