### ISSUE TITLE
Change quotation mark to double for the condition

### ISSUE THREAD

**Issue by Jenga01** [LaravelDaily/laravel-charts#47]
In LaravelChart.php line 53
`[['name' => '', 'condition' => '', 'color' => '']];`
change to
`[['name' => '', 'condition' => "", 'color' => '']];`

Because right it would accept only strings, I found it very useful when I can pass some variable data.

**Comment by PovilasKorop** [comment]
@Jenga01 please make a pull request

**Comment by Jenga01** [comment]
pull request made
