### ISSUE TITLE
Limit Number of Records Displayed on the Chart

### ISSUE THREAD

**Issue by Kayla-Lamp** [LaravelDaily/laravel-charts#49]
Hi there,

Is there currently a way to limit the number of groups pulled through and displayed on the chart (only show top 10 results)?

Thanks in advance for your response.

**Comment by PovilasKorop** [comment]
@Kayla-Lamp currently there's no such feature. But if you're happy to build it, we can accept it as a Pull Request.

**Comment by PovilasKorop** [comment]
Fixed by https://github.com/LaravelDaily/laravel-charts/pull/66
