### ISSUE TITLE
the chart is not rendering

### ISSUE THREAD

**Issue by ynroot** [LaravelDaily/laravel-charts#53]
the chart is not rendering, but when I use dd (chart_name) I see that the object has the data I need, I'm just not getting it to appear in the desired view.

Can anyone help me with this problem?

Using version
laraveldaily / laravel-charts ^ 0.1.25
laravel 8.12

**Comment by PovilasKorop** [comment]
@ynroot 

1. do you have any errors in `storage/logs/laravel.log` or in the browser console?
2. What are the parameters of your LaravelChart call, can you provide a full list of parameters?

**Comment by ynroot** [comment]
@PovilasKorop 

I don't know why but before it was like this it didn't render

`@section ('javascript')
{!! $ chart1-> renderChartJsLibrary () !!}
{!! $ chart1-> renderJs () !!}
@endsection`

when I put it in my content section it rendered

`@section ('content')

         <h1> {{$ chart1-> options ['chart_title']}} </h1>
          {!! $ chart1-> renderHtml () !!}

{!! $ chart1-> renderChartJsLibrary () !!}
{!! $ chart1-> renderJs () !!}
@endsection`

**Comment by PovilasKorop** [comment]
@ynroot it depends on where your "javascript" section is, maybe you don't even have it?

But if it works for you now, please close the issue.
