### ISSUE TITLE
How to specify which column in model should be used as dataset? 

### ISSUE THREAD

**Issue by Sjos12** [LaravelDaily/laravel-charts#61]
I have a model with some columns. I want a certain column to be used as the dataset and another column to be used on the x-axis as labels. I got the x-axis labels to work but can't seem to specifiy which column should be used in the model for the dataset. It now seems to be using the 'id' column on my model, I want to use the 'value' column instead. Here's my code. 

```
$options = [
            'chart_title' => 'Samplechart',
            'chart_type' => 'line',
            'model' => 'App\Models\Entry',
            'condition' => [
                ['name' => 'value', 'condition' => 'user_id = {Auth::user()->id}', 'color' => 'black', 'fill' => 'true'],
            ],
            'report_type' => 'group_by_date', 
            'group_by_field' => 'added_at',
            'group_by_period' => 'day',
            'group_by_field_format' => 'Y-m-d',
        ]; 

 $chart = new LaravelChart($options);
```
Can someone tell me where in the docs this is specified or is this feature not supported?

Thanks!

**Comment by PovilasKorop** [comment]
@Sjos12 from Readme:

```
    'aggregate_function' => 'sum',
    'aggregate_field' => 'amount',
    'aggregate_transform' => function($value) {
        return round($value / 100, 2);
    }
```

**Comment by Sjos12** [comment]
Thanks that worked. But isn't the aggregate option only supposed to be added when you want to manipulate the data that is given. Can you explain why it works?

**Comment by PovilasKorop** [comment]
@Sjos12 I suggest you install Laravel Debugbar package and see for yourself what queries are executed for grouping
