### ISSUE TITLE
ErrorException while using LaravelChart in Laravel-Employee-Attendance-Reports project

### ISSUE THREAD

**Issue by kyaroslav** [LaravelDaily/laravel-charts#81]
Example usage in Controller

```
            $chart = new LaravelChart([
                'chart_title'           => 'Hours of work per day',
                'chart_type'            => 'line',
                'report_type'           => 'group_by_date',
                'model'                 => 'App\\TimeEntry',
                'group_by_field'        => 'time_start',
                'group_by_period'       => 'day',
                'aggregate_function'    => 'sum',
                'aggregate_field'       => 'total_time_chart',
                'column_class'          => 'col-md-8',
                'continuous_time'       => true,
            ]);
```
Steps to reproduce in an Example project "[Laravel-Employee-Attendance-Reports](https://github.com/LaravelDaily/Laravel-Employee-Attendance-Reports)"
1. Install project and seed example data
2. login as admin
3. go to  page /admin/reports?employee=11
Error appears
<img width="1202" alt="Screenshot 2022-01-03 at 19 42 40" src="https://user-images.githubusercontent.com/389143/147962121-4b1fb8a7-0a41-41bd-b264-3a05f149c35a.png">

**Comment by PovilasKorop** [comment]
@kyaroslav thanks for your fix #82 - I've merged and released a new package version `0.1.29` - will that fix the issue in the employee attendance report?

**Comment by kyaroslav** [comment]
@PovilasKorop Yes, now the issue in the employee attendance report is fixed. Just need to use `composer update` command , composer install will install `"laraveldaily/laravel-charts": "^0.1.13"` according to composer.json.

**Comment by PovilasKorop** [comment]
@kyaroslav great to hear!
