### ISSUE TITLE
Undefined array key "data"

### ISSUE THREAD

**Issue by devscript-abdo** [LaravelDaily/laravel-charts#87]
Undefined array key "data"
vendor\laraveldaily\laravel-charts\src\views\javascript.blade.php

   data: {

            labels: [

                @if (count($datasets) > 0)

                    @foreach ($datasets[0]['data'] as $group => $result)

                        "{{ $group }}",

                    @endforeach

                @endif

Laravel 8

**Comment by devscript-abdo** [comment]
Fixed it's a error by me 
        $chart_options = [
            'chart_title' => 'Users by months',
            'report_type' => 'group_by_date',
            'model' => 'App\Models\Sameleon\User',
            'group_by_field' => 'created_at',
            'group_by_period' => 'month',
            'chart_type' => 'bar',
            'filter_field' => 'created_at',
            'filter_days' => 30, // show only last 30 days
        ];

I have a Folder named "Sameleon" in Moldes Directory so i forget to put them in the Model key :  'model' => 'App\Models\Sameleon\User',

------

**Comment by richyzak** [comment]
I got same problem

**Comment by elmarzouguidev** [comment]
@richyzak the problem is coming from the Namespace of the Model verify your Model's namespace
