### ISSUE TITLE
NoSQL Compatibility

### ISSUE THREAD

**Issue by gogl92** [LaravelDaily/laravel-charts#94]
Has anyone ever used this package with mongodb or other NoSQL database engine?

I'll give it a try next weekend but wondering if someone have tried this before.

Also at @inquid we are considering sponsoring devs to work on some fixes/new features to this extension to make it usable in our client projects, if anyone is interested.

**Comment by PovilasKorop** [comment]
@gogl92 we haven't tested it with NoSQL engine, but under the hood the package runs Eloquent queries, so the same NoSQL driver rules may apply.

Not interested in sponsorship at the moment, no free time available at the moment at all, no matter free or paid.

**Comment by gogl92** [comment]
@PovilasKorop thanks, I'll update this issue after testing it with MongoDB

**Comment by gogl92** [comment]
@PovilasKorop Looks like we can close this issue, I've been making some tests with MongoDB and it's working as expected 👍🏼  
![image](https://user-images.githubusercontent.com/1505641/216240883-199aec6d-8933-4f1f-ab86-625d70b8188d.png)

**Comment by PovilasKorop** [comment]
@gogl92 great! Thanks for reporting.
