### ISSUE TITLE
Allow user to modify labels

### ISSUE THREAD

**Issue by sonichandni** [LaravelDaily/laravel-charts#98]
$campaign_status_options = [
            'chart_title' => 'Campaigns status',
            'report_type' => 'group_by_string',
            'model' => 'App\Campaign',
            'group_by_field' => 'created_at',
            'group_by_period' => 'day',
            'chart_type' => 'pie',
            'group_by_field' => 'status',
            'labels' => [
                    '0' => 'Draft',
                    '1' => 'Pending',
                    '2' => 'Approved',
                    '3' => 'Image Creating',
                    '4' => 'Image Created',
                    '5' => 'Message Sending',
                    '6' => 'Completed',
                    '7' => 'Cancelled'
                ],
            
        ];

I want to achieve this kind of thing for my chart, for that I have made changes in LaravelChart.php file.

Thanks

**Comment by PovilasKorop** [comment]
@sonichandni we don't have this feature and didn't plan it, but if you submit a Pull Request with automated tests, then I will check it out.

**Comment by sonichandni** [comment]
Hello @PovilasKorop thank you for your quick replay, I have created a pull request for the same,  it's #99
